---

- hosts: master peer1 peer2 head1 head2 head3 deployment1
  become: yes
  become_method: sudo

  vars:
   - splunk_binpath: "{{ lookup('pipe', 'ls /opt/deployment/splunk_bin/splunk-*.tgz | head -1') }}"
   - template_hosts: "hosts"
   - splunk_installpath: /opt
   - localzone: Europe/Paris

  tasks:

############################## Deploy Splunk ##############################

  - name: Create the system splunk account for splunk
    user: name=splunk comment="system account for Splunk" shell=/bin/bash state=present

  # Verify if Splunk is already installed
  - name: Check if Splunk path exists
    stat: path={{ splunk_installpath }}/splunk
    register: check_splunk_path

  # Copy and unarchive Splunk
  - name: Copy and unarchive Splunk
    unarchive: src={{ splunk_binpath }} dest={{ splunk_installpath }} owner=splunk group=splunk
    when: check_splunk_path.stat.exists == false

  # Start and accept licence (run async)
  - name: Start Splunk and accept licence
    command: "{{ splunk_installpath }}/splunk/bin/splunk start --answer-yes --no-prompt --accept-license"
    async: 60
    poll: 5
    become: yes
    become_user: splunk
    ignore_errors: yes

  # Enable boot-start
  - name: Enable boot start for Splunk
    command: "{{ splunk_installpath }}/splunk/bin/splunk enable boot-start -user splunk"
    ignore_errors: yes

  # Lower the minimal volume of free space required
  - name: Lower the minimal free space required (default 5GB, set to 1 GB to fit VMs space)
    command: "{{ splunk_installpath }}/splunk/bin/splunk set minfreemb 1000 -auth admin:changeme"
    become: yes
    become_user: splunk
    ignore_errors: yes

  # Start service (dont' wait for service to start)
  - name: Start Splunk service
    service: name=splunk state=started
    async: 60
    poll: 0

  # Wait for service startup
  - name: Wait for Splunk startup
    wait_for: port=8089 timeout=30
    ignore_errors: yes

  # Change default admin password to admin to allow remote connections
  - name: Set the admin default password to admin
    command: "{{ splunk_installpath }}/splunk/bin/splunk edit user admin -password 'admin' -auth admin:changeme"
    ignore_errors: yes
    become: yes
    become_user: splunk

############################## ssh config ##############################

# Deploy the ssh rsa public key

- hosts: master
  become: yes
  become_method: sudo

  tasks:

  - name: Create the .ssh directory
    file: path=/home/splunk/.ssh state=directory mode=0700 owner=splunk group=splunk

  - name: Deploy the private key on the master node
    copy: src=id_rsa dest=/home/splunk/.ssh/id_rsa owner=splunk group=splunk mode=0600

  - name: Deploy the public key on the master node
    copy: src=id_rsa.pub dest=/home/splunk/.ssh/id_rsa.pub owner=splunk group=splunk mode=0600

- hosts: peer1 peer2 head1 head2 head3 deployment1
  become: yes
  become_method: sudo

  tasks:

  - name: Deploy the public key for the splunk user
    authorized_key: user=splunk key="{{ lookup('file', 'id_rsa.pub') }}"

# Prevent SSH from asking confirmation for the first connexion

- hosts: master
  become: yes
  become_method: sudo

  tasks:

  - name: SSH Strict host checking deactivation
    lineinfile: dest=/home/splunk/.ssh/config line="StrictHostKeyChecking no" create=yes owner=splunk group=splunk
