---

- hosts: all
  become: yes
  become_method: sudo

  vars_files:
   - vars/global_vars.yml

# Run roles
  roles:
    - common

  tasks:

############################## Set Timezone ##############################

  - name: Check the current timezone
    shell: 'timedatectl status | grep "zone" | sed -e "s/^[ ]*Time zone: \(.*\) (.*)$/\1/g"'
    register: timezone_value

  # Store the host timezone
  - set_fact: timezone_value={{ timezone_value.stdout }}

  - name: Set timezone variables for Debian / Ubuntu
    file: src=/usr/share/zoneinfo/{{ localzone }} dest=/etc/localtime owner=root group=root state=link force=yes
    notify: update tzdata
    when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and timezone_value!="{{ localzone }}"

############################## update hosts ##############################

  - name: Update hosts file
    action: template src={{ template_hosts }} dest=/etc/hosts

############################## handlers ##############################

  handlers:

    - name: update tzdata
      command: dpkg-reconfigure --frontend noninteractive tzdata
