---

- block:

  - name: Create swapfile
    command: dd if=/dev/zero of={{ swap_path }} bs={{ dd_bs_size_mb }}M count={{ swap_count }} creates={{ swap_path }}
    register: write_swapfile

  - name: Set swapfile permissions
    file: path={{ swap_path }} mode=600

  - name: Build swapfile
    command: mkswap {{ swap_path }}
    register: create_swapfile
    when: (write_swapfile.changed)

  - name: Enable swapfile
    command: swapon {{ swap_path }}
    when: (create_swapfile.changed)

  - name: Add swapfile to /etc/fstab
    lineinfile: dest=/etc/fstab line="{{ swap_path }}   none    swap    sw    0   0" state=present

  - name: Disable THP in live
    shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"

  - name: Disable THP at boot time
    lineinfile: dest=/etc/rc.local state=present insertbefore=exit\s0 line="echo never > /sys/kernel/mm/transparent_hugepage/enabled"

  - name: Disable THP defrag in live
    shell: "echo never > /sys/kernel/mm/transparent_hugepage/defrag"

  - name: Disable THP defrag at boot time
    lineinfile: dest=/etc/rc.local state=present insertbefore=exit\s0 line="echo never > /sys/kernel/mm/transparent_hugepage/defrag"

  when: container is not defined

# ulimits settings,
# https://answers.splunk.com/answers/223838/why-are-my-ulimits-settings-not-being-respected-on.html
- name: Incresing ulimits open files and number of processes (nofile / nproc)
  blockinfile:
    dest: /etc/security/limits.conf
    state: present
    insertbefore: '#\sEnd\sof\sfile'
    content: |
      splunk hard nofile 20240
      splunk soft nofile 10240
      splunk hard nproc  100000
      splunk soft nproc  100000

- name: Adding load of ulimit from pam.d
  blockinfile:
    dest: /etc/pam.d/common-session
    state: present
    insertbefore: '#\send\sof\spam-auth-update\sconfig'
    content: |
      # Ensure we load ulimits set in /etc/security.limits.conf
      session required pam_limits.so

- name: Load pam_limits for system ulimits
  lineinfile: dest=/etc/rc.local state=present insertbefore="#\send\sof\spam-auth-update\sconfig" line="session required pam_limits.so"

- name: Disable atime in fstab
  replace: dest=/etc/fstab regexp="(.*\/\s*ext4\s*)defaults(\s.*)" replace="\1defaults,noatime\2"
